[versions]
velocity = "3.4.0-SNAPSHOT"

[libraries]
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
sprax-lime = { module = "de.sprax2013.lime:lime-api", version = "0.0.4-SNAPSHOT" }
j256-twoFactorAuth = { module = "com.j256.two-factor-auth:two-factor-auth", version = "1.3" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.10" }

[plugins]
jetbrains-ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.2" }
runVelocity = { id = "xyz.jpenilla.run-velocity", version = "2.3.1" }
shadow = { id = "com.gradleup.shadow", version = "9.0.0-rc1" }
sonarqube = { id = "org.sonarqube", version = "6.2.0.5505" }
